## -----------------------------------------------tink--------------------------------------
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: "{{ .Release.Name }}-tink"
spec:
  http:
    - name: tink
      match:
        paths:
          - /apis/tink/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
          - CONNECT
          - TRACE
        exprs:
        - subject:
            scope: Header
            name: x-atop-version
          op: Equal
          value: "{{ .Chart.AppVersion }}"          
      plugins:
        - name: key-auth
          enable: true
          config:
            key: admin
            header: Authorization
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /apis/tink/
              - /
      websocket: true
      backends:
        - serviceName: "{{ .Release.Name }}-tink"
          servicePort: 8003

---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: "{{ .Release.Name }}-tink"
spec:
  scheme: http
  loadbalancer:
    type: roundrobin

## -----------------------------------------------files--------------------------------------
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: "{{ .Release.Name }}-files"
spec:
  http:
    - name: files
      match:
        paths:
          - /apis/files/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
          - CONNECT
          - TRACE
        exprs:
        - subject:
            scope: Header
            name: x-atop-version
          op: Equal
          value: "{{ .Chart.AppVersion }}"          
      plugins:
        - name: key-auth
          enable: true
          config:
            key: admin
            header: Authorization      
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /apis/files/
              - /
      websocket: true
      backends:
        - serviceName: "{{ .Release.Name }}-files"
          servicePort: 8004

---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: "{{ .Release.Name }}-files"
spec:
  scheme: http
  loadbalancer:
    type: roundrobin

## -----------------------------------------------analysis--------------------------------------
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: "{{ .Release.Name }}-analysis"
spec:
  http:
    - name: analysis
      match:
        paths:
          - /apis/analysis/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
          - OPTIONS
          - CONNECT
          - TRACE
        exprs:
        - subject:
            scope: Header
            name: x-atop-version
          op: Equal
          value: "{{ .Chart.AppVersion }}"          
      plugins:
        - name: key-auth
          enable: true
          config:
            key: admin
            header: Authorization      
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /apis/analysis/
              - /
      websocket: true
      backends:
        - serviceName: "{{ .Release.Name }}-analysis"
          servicePort: 8005

---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: "{{ .Release.Name }}-analysis"
spec:
  scheme: http
  loadbalancer:
    type: roundrobin
